version: '3'

services:

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./client
    image: "react-frontend:latest"
    networks:
      - app-network

  backend:
    build: ./server
    image: "flask-backend:latest"
    networks:
      - app-network
    ports:
      - 5000:5000
      - 10001:10001
    environment:
      - DEBUGGER=1 

  revproxy:
    build: ./proxy
    image: "reverse-proxy:latest"
    networks:
      - app-network
    ports:
      - "8000:80"
 

networks:
  app-network:

volumes:
    postgres:
    pgadmin: